spin_manifest_version = 2

# General identification information
[application]
name = "xxx"
version = "0.2.0"
description = "xxx"

[variables]
redis_host = { required = true }  # will be filled out in ENV
proto_id = { required = true }  # will be filled out in ENV

[[trigger.redis]]
address = "redis://{{redis_host}}:6379"
channel = "vin2worker:{{proto_id}}"
component = "xxx"

[component.xxx]
description = ""
source = "target/wasm32-wasi/release/xxx.wasm"

[component.xxx.variables]
redis_host = "{{ redis_host }}"
proto_id = "{{ proto_id }}"

# How to build the Wasm module from source
[component.xxx.build]
command = "cargo build --target wasm32-wasi --release"
